gatling {
  reportportal {
    # endpoint = "http://localhost:8080"
    # apiKey = ""
    # project = "default_personal"
    # launch = "Gatling Performance Metrics"
    # sla {
    #   p95Ms = ""
    #   p99Ms = ""
    #   errorRatePct = ""
    # }
    # sample {
    #   includeRegex = ""
    #   excludeRegex = ""
    # }
    # attributes = []
  }
}
